### ISSUE TITLE
Broken link to GitHub

### ISSUE THREAD

**Issue by gonsie** [jonathanabennett/jonathanabennett.github.io#1]
Hi, I hope you don’t mind me opening an issue. 

The link to GitHub should be “https://github.com/jonathanabennett/jonathanabennett.github.io.git” but it is appearing as “https://jonathanabennett/jonathanabennett.github.io.git”.

I’m very excited to read your blog!

**Comment by jonathanabennett** [comment]
Thanks! This helped a ton, actually. I've updated the settings, but the new settings won't appear until I push my next change. I'm pretty sure I have to actually push a new page, in which case it won't change until the weekend, but I'll try pushing without a new page and see if the change takes.

**Comment by gonsie** [comment]
Also, I'm not sure how you are generating your RSS feed, but if you could put the full post text in the feed, that would be useful.

Keep up the great work!
