### ISSUE TITLE
Missing: 2019-06-13  »  Python and Emacs Pt. 1

### ISSUE THREAD

**Issue by bhyde** [jonathanabennett/jonathanabennett.github.io#2]
Looks like it didn’t make into the repo, so the link in the blog is 404.

**Comment by jonathanabennett** [comment]
Yeah, I started it and realized I needed more time to finish it, so I switched to the org2web post for last week's blog. Sadly, I haven't fixed all the bugs in my usage of org2web. Even though I intentionally didn't select the Python page to upload, it still generated all the links.

I uploaded it yesterday, it should be available now.
